[config]
type = "pipeline"
chartbook_format_version = "0.0.2"

[site]
title = "p09_koijen_yogo_2020"
author = "Allen Wu & Nandini Krishnan & Xiongfei Wang"
copyright = "2025"
logo_path = ""
favicon_path = ""

[pipeline]
id = "P0"
pipeline_name = "p09_koijen_yogo_2020"
pipeline_description = "Our replication"
lead_pipeline_developer = "Allen Wu & Nandini Krishnan & Xiongfei Wang"
contributors = ["Allen Wu & Nandini Krishnan & Xiongfei Wang"]
software_modules_command = "module load anaconda3/3.11.4 TeXLive/2023"
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = ""
README_file_path = "./README.md"

[notebooks]




[dataframes]


[dataframes.bis]
dataframe_name = "BIS Debt securities statistics"
short_description_df = "borrowing and investment activities in debt capital markets"
data_sources = ["National data", "BIS calculations"]
data_providers = ["National data", "BIS calculations"]
links_to_data_providers = ["https://data.bis.org/topics/DSS/data?data_view=table"]
topic_tags = ["Debt Security", "Repo"]
type_of_data_access = "Public"
data_license = "No"
license_expiration_date = "N/A"
need_to_contact_provider = "No"
provider_contact_info = ""
restriction_on_use = "No"
how_is_pulled = "Web API via Python and Pandas"
path_to_parquet_data = "./_data/bis_debt_securities_cleaned.parquet"
path_to_excel_data = ""
date_col = "date"
dataframe_docs_path = "./docs_src/dataframes/bis_debt_secutities_statistics.md"


[charts]


[charts.bis_chart]
chart_name = "Average OBS_VALUE by Sector (Annualized)"
short_description_chart = "Calculate average OBS_Value by sector"
dataframe_id = "bis"
path_to_html_chart = "./_output/obs_value_by_sector.html"
chart_docs_path = "./docs_src/charts/bis_chart.md"
